base_url: "https://semantic-brandea-banao-dc049ed0.koyeb.app"

credentials:
  username: "admin"
  password: "password"

auth:
  login_endpoint: "/login"

endpoints:
  tenants: "/api/tenant"
  virtual_services: "/api/virtualservice"
  service_engines: "/api/serviceengine"
